=== bvantuan/parseme-utilities/st-organizers/release-preparation/configs/config-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Schema configuration file for the re-annotation script",
  "type": "object",
  "properties": {
    "language": {
      "description": "2-letter iso code of the language",
      "type": "string",
      "pattern": "^[A-Z]{2}$"
    },
    "treebank": {
      "description": "A file .conllu or a directory of treebanks of Universal Dependencies (UD)",
      "type": "string",
      "minLength": 1
    },
    "uri": {
      "description": "The persistent URI of the original corpus",
      "type": "string",
      "minLength": 1
    },
    "language_repository": {
      "description": "The language repository path in local",
      "type": "string",
      "minLength": 1
    },
    "verbose": {
      "description": "The verbose option, display detailed processing information",
      "type": "boolean"
    },
    "source": {
      "description": "Files .cupt to reannotate",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "corpus": {
            "description": "A file .cupt to reannotate",
            "type": "string",
            "pattern": "^.*\\.cupt$"
          },
          "method": {
            "description": "Method of reannotation (supported udtreebank and udpipe)",
            "type": "string",
            "enum": ["udpipe", "udtreebank"]
          },
          "tagger": {
            "description": "Reannotate columns LEMMA, UPOS, XPOS and FEATS in udpipe method",
            "type": "boolean"
          },
          "parser": {
            "description": "Reannotate columns HEAD and DEPREL in udpipe method",
            "type": "boolean"
          }
        },
        "required": ["corpus", "method"],
        "additionalProperties": false
      }
    }
  },
  "required": ["language", "treebank", "uri", "language_repository", "verbose", "source"]
}

=== bvantuan/parseme-utilities/lang-leaders/morphosyntax-update/configs/config_EN.json
{
  "language": "EN",
  "treebank": "/home/tuan/Documents/parseme/UD/UD_English",
  "uri": "http://hdl.handle.net/11234/1-4923",
  "language_repository": "/home/tuan/Documents/parseme_dev/parseme_corpus_en",
  "verbose": false,
  "source": [
    {
      "corpus": "train.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "test.cupt",
      "method": "udtreebank"
    }
  ]
}

=== bvantuan/parseme-utilities/st-organizers/release-preparation/configs/config_PL.json
{
  "language": "PL",
  "treebank": "/home/tuan/Documents/parseme/UD/ud-treebanks-v2.11/UD_Polish-PDB",
  "uri": "http://hdl.handle.net/11234/1-4923",
  "language_repository": "/home/tuan/Documents/parseme_dev/parseme_corpus_pl",
  "verbose": false,
  "source": [
    {
      "corpus": "NKJP.cupt",
      "method": "udpipe",
      "tagger": false,
      "parser": true
    },
    {
      "corpus": "PCC.cupt",
      "method": "udpipe",
      "tagger": true,
      "parser": true
    },
    {
      "corpus": "PDB.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-dev-110-200-320.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-dev-NEWS.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-dev-OTHER.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-test-110-200-320.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-test-NEWS.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-test-OTHER.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-train-110-200-320.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-train-NEWS.cupt",
      "method": "udtreebank"
    },
    {
      "corpus": "pl-pdb-ud-train-OTHER.cupt",
      "method": "udtreebank"
    }
  ]
}
